version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: jpco0/wallet_postgres_frontend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: wallet_api_homolog
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wallet_network

  app:
    build: ./backend
    container_name: wallet_api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: wallet_api_homolog
      DB_DRIVER: postgresql+psycopg2
      TAXA_SAQUE_PERCENTUAL: 0.01
      TAXA_CONVERSAO_PERCENTUAL: 0.02
      TAXA_TRANSFERENCIA_PERCENTUAL: 0.01
      COINBASE_API_BASE_URL: https://api.coinbase.com/v2/prices
      SECRET_KEY: your-secret-key-here
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - wallet_network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: wallet-frontend:latest
    container_name: wallet_frontend
    ports:
      - "8080:80"
    depends_on:
      - app
    networks:
      - wallet_network

volumes:
  postgres_data:

networks:
  wallet_network:
    driver: bridge
